#!/usr/bin/env python
# Usage: examples/logistic_regression examples.db:track_hello
from sys import argv
from itertools import groupby, islice
from operator import itemgetter
from random import Random

import matplotlib
matplotlib.use("pdf")
import matplotlib.pyplot as plt

import twitterology as tw
import twitterology.features as tf
from model import MODEL

import numpy as np
np.set_printoptions(precision=2, suppress=True)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve, auc
from sklearn.cross_validation import cross_val_score, StratifiedKFold

from tqdm import tqdm


def link_to(user_id):
    return "https://twitter.com/intent/user?user_id=" + user_id


def main():
    """
    database, table = argv[1].split(":")
    storage = tw.sources.sqlite(database, table)
    """

    samples_a = dict(np.load("db/samples_a.npy"))
    samples_b = dict(np.load("db/samples_b.npy"))

    estimates = np.load("db/estimates.npy")
    coef = np.load("db/coef.npy")

    for user_a, user_b, proba in estimates:
        proba = float(proba)
        if proba > 0.999 and user_a != user_b:
            print link_to(user_a)
            print samples_a[user_a]
            print
            print link_to(user_b)
            print samples_b[user_b]
            print
            print MODEL.difference(samples_a[user_a], samples_b[user_b]) * coef
            print "\n======\n\n\n"


if __name__ == "__main__":
    main()
