#!/usr/bin/env python
# Usage: examples/logistic_regression examples.db:track_hello
from sys import argv
from itertools import groupby, islice
from operator import itemgetter
from random import Random

import matplotlib
matplotlib.use("pdf")
import matplotlib.pyplot as plt

import twitterology as tw
import twitterology.features as tf


import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve, auc
from sklearn.cross_validation import cross_val_score, StratifiedKFold

from tqdm import tqdm


def main():
    samples = np.loadtxt("db/samples.gz")
    targets = np.loadtxt("db/targets.gz")

    splitter = StratifiedKFold(
        targets, n_folds=10,
        random_state=123, shuffle=True
    )
    for tr_idx, ts_idx in splitter:
        print "train:", targets[tr_idx].sum(), "/", len(targets[tr_idx])
        print "test:", targets[ts_idx].sum(), "/", len(targets[ts_idx])

    clf = LogisticRegression()
    roc_aucs = cross_val_score(
        clf, samples, targets,
        cv=splitter, scoring="roc_auc"
    )
    print roc_aucs, np.average(roc_aucs)

    train_indices, test_indices = next(iter(splitter))
    train_samples, train_targets = samples[train_indices], targets[train_indices]
    test_samples, test_targets = samples[test_indices], targets[test_indices]

    clf.fit(train_samples, train_targets)
    probs = clf.predict_proba(test_samples)
    false_positives, true_positives, _ = roc_curve(test_targets, probs[:, 1])
    roc_auc = auc(false_positives, true_positives)

    plt.figure(figsize=(7, 7))
    plt.plot(false_positives, true_positives, label="AUC: {}".format(roc_auc))
    plt.legend(loc="lower right")
    plt.grid()
    plt.savefig("roc")


if __name__ == "__main__":
    main()
